### ISSUE TITLE
Loading HDF5 datasets crash because data_dictionary["example names"] is set to None

### ISSUE THREAD

**Issue by znamensk** [scvae/scvae#13]
Hi, first of all, great work! Looking forward to experimenting with the model.

I had an issue loading a dataset in HDF5 format as described in the docs: it kept crashing when splitting data because `data_dictionary["example names"]` was set to None. I think the cause is that `return list_of_names` statement is missing in the following function:

https://github.com/scvae/scvae/blob/2f590ca5aafd951dfd0b70842101a27e6315b619/scvae/data/loaders.py#L711

**Comment by chgroenbech** [comment]
Thanks for the heads-up.

I've fixed this in the next version.
