### ISSUE TITLE
Training and validation loss becomes NaN

### ISSUE THREAD

**Issue by gprashant123** [scvae/scvae#15]
While training the model, the ELBO of the training data or validation data or both sometimes becomes `nan` as it progresses, as shown below:

```
Epoch 99 (10.4 s):
    Evaluating model.
    Training set (3.42 s): ELBO: -1709.1, ENRE: -1692.1, KL: 16.986.
    Validation set (840 ms): ELBO: nan, ENRE: -inf, KL: 17.461.
    Saving model parameters.
    Model parameters saved (434 ms).

Step 4658 (213 ms): -1675.1.
Step 4662 (222 ms): -1843.4.
Step 4667 (216 ms): -1464.6.
Step 4672 (215 ms): -1736.6.
Step 4677 (219 ms): -1577.7.
Step 4681 (220 ms): -1729.2.
Step 4686 (221 ms): -1591.9.
Step 4691 (221 ms): -1784.
Step 4695 (217 ms): -1624.3.
Step 4700 (118 ms): -1770.2.

Epoch 100 (10.5 s):
    Evaluating model.
    Training set (3.4 s): ELBO: nan, ENRE: -inf, KL: 17.066.
    Validation set (858 ms): ELBO: nan, ENRE: -inf, KL: 17.572.
    Saving model parameters.
``` 
Due to this, the evaluation step also fails mostly as the ELBO of the test set goes to `nan`.

```
Best-model evaluation
---------------------

Evaluating trained model for run 13 on original values.
    Test set (1.36 s):  ELBO: nan, ENRE: -inf, KL: 20.367.
/usr/local/lib/python3.6/dist-packages/scvae/data/data_set.py:537: RuntimeWarning: invalid value encountered in true_divide
  self.normalised_count_sum = self.count_sum / self.count_sum.max()
```

```
Data set        mean   std. dev.   dispersion   minimum    maximum   sparsity
original       0.6013     25.922     1117.5     0            15631        0.87985
reconstructed  inf        nan        nan        3.3546e-10   inf          0.92008
```

and the following error shows up:
`ValueError: supplied range of [3.3546437849807376e-10, inf] is not finite`

I am currently trying to increase/decrease the number of epochs to bypass this issue. Otherwise, is there any other way?

I would also like to know if scVAE, when implemented on Google Colab, automatically makes use of GPU or we have to manually change it. I get a Colab warning that GPU is not utilised while training and it recommends to connect to local runtime.

**Comment by chgroenbech** [comment]
This usually happens when the chosen reconstruction distribution (likelihood function) is not fit for the data set. Have you another distribution? Right now, the training will only be aborted if the ELBO for a batch becomes indefinite during training. I have added additional checks for the training and validation sets in the next version. So you should be able to evaluate the model afterwards.

I have not used Google Colab, so I'm not familiar with it. When I use scVAE on a local machine, TensorFlow use all available resources unless I limit it.

**Comment by gprashant123** [comment]
I am currently using ZINB distribution and I have not tried other distributions. Thanks for adding the additional checks!

**Comment by wenyuhaokikika** [comment]
> This usually happens when the chosen reconstruction distribution (likelihood function) is not fit for the data set. Have you another distribution? Right now, the training will only be aborted if the ELBO for a batch becomes indefinite during training. I have added additional checks for the training and validation sets in the next version. So you should be able to evaluate the model afterwards.
> 
> I have not used Google Colab, so I'm not familiar with it. When I use scVAE on a local machine, TensorFlow use all available resources unless I limit it.

Sorry, I am using scvae version 2.1.4, but when I run it, I notice that it is still running on the CPU.

For example, in the code snippet at https://github.com/scvae/scvae/blob/d6148efabfb12eda8bd1b895e1bb72f592e39ab0/scvae/cli.py#L629C9-L629C9, if I want to run it on the GPU, I usually specify `model = model.to(device)`. In TensorFlow, I might use with `tf.device('/gpu:0')`, but I haven't found a similar option here. The entire training process is happening on the CPU. If I am mistaken, please point out my error and let me know how to train on the GPU. If my understanding is correct, would it be possible to add an option like `scvae train --gpu-id 0`?
