### ISSUE TITLE
Multiple h5 for processing and tissue integration

### ISSUE THREAD

**Issue by cartal** [scvae/scvae#3]
Hi, 

Thank you for developing this tool. It looks really promising. 
I am trying to analyse multiple datasets of the same tissue and I would like to process them at once. So I have a couple of questions:

1) How do I feed .h5 files to scVAE?
2) Would it be possible to perform dataset integration a la Seurat (RunMultiCCA) with scVAE?

Looking forward to hearing from you.

**Comment by chgroenbech** [comment]
In the next major update, we will add support for more data formats, including H5. We’ll look into your other question as part of this.

**Comment by yejg2017** [comment]
Hi,
 When I feed the single cell 10X data in .h5 format,and I got the error:ValueError: Data format `h5` not recognised.How can I solve this issue?

**Comment by chgroenbech** [comment]
I have added support for loading H5 directly in the next release.

For now, try reading H5 files using the 10x Genomics format by adding `–format 10x` to your command.

@cartal, as for your second question in your comment, can you open another issue with some more detail, if you’re still interested in this functionality?
