### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'required'

### ISSUE THREAD

**Issue by xuebaliang** [scvae/scvae#8]
hello, when I run your code "scvae train 10x-PBMC-PP --split-data-set -m GMVAE -r negative_binomial -l 100 -H 100 100 -w 200 -e 500", the error occurs like below:
Traceback (most recent call last):
  File "/data/chenliang/anaconda3/envs/tensorflow/bin/scvae", line 10, in <module>
    sys.exit(main())
  File "/data/chenliang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/scvae/cli.py", line 697, in main
    help="commands", dest="command", required=True)
  File "/data/chenliang/anaconda3/envs/tensorflow/lib/python3.6/argparse.py", line 1707, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'

It seems to there has one bug in your cli.py file. Therefore can you tell me how i should do next? Thanks!

**Comment by ForrestCKoch** [comment]
I have just come across this problem as well and found a solution elsewhere.  It seems that despite claiming to only require Python >= 3.5, you in fact need 3.7

> The `add_subparsers` command didn't support the `required` option until Python 3.7. See https://github.com/python/cpython/pull/3027.
> 
> Upgrading to Python 3.7 or later should resolve the issue.
> 
> _Originally posted by @pkoenig10 in https://github.com/pkoenig10/sink/issues/16#issuecomment-421830751_

I would be interested in a fix that doesn't require me to install a new version of python though ...

**Comment by chgroenbech** [comment]
I have fixed this for the next release.
